# Generated by Django 5.1.2 on 2024-10-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagoEnCuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cuotas', models.IntegerField()),
                ('banco', models.CharField(max_length=10)),
                ('importe', models.FloatField()),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=50)),
            ],
        ),
    ]
