# Generated by Django 5.1.2 on 2024-11-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_en_cuotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoencuotas',
            name='banco',
            field=models.CharField(choices=[('Santander', 'Santander'), ('Galicia', 'Galicia'), ('BBVA', 'BBVA'), ('Macro', 'Macro'), ('Superville', 'Superville')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pagoencuotas',
            name='cantidad_cuotas',
            field=models.IntegerField(choices=[(1, 1), (3, 3), (6, 6), (12, 12), (18, 18), (24, 24)]),
        ),
    ]
