# Generated by Django 5.1.2 on 2024-10-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo_dinero',
            name='tipo_de_flujo',
            field=models.CharField(default='Ingreso', max_length=7),
            preserve_default=False,
        ),
    ]
