# Generated by Django 5.1.2 on 2024-10-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_flujo_dinero_tipo_de_flujo'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo_dinero',
            name='tipo',
            field=models.CharField(default='Servicios', max_length=15),
            preserve_default=False,
        ),
    ]
