# Generated by Django 5.1.2 on 2024-10-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_flujo_dinero_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujo_dinero',
            name='tipo_de_flujo',
            field=models.CharField(max_length=15),
        ),
    ]
