# Generated by Django 5.1.2 on 2024-10-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_flujo_dinero_tipo_de_flujo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flujo_dinero',
            old_name='tipo_de_flujo',
            new_name='tipoflujo',
        ),
    ]
