# Generated by Django 5.1.2 on 2024-10-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_rename_tipo_de_flujo_flujo_dinero_tipoflujo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flujo_dinero',
            old_name='tipoflujo',
            new_name='tipo_de_flujo',
        ),
    ]
