# Generated by Django 5.1.2 on 2024-11-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_rename_tipoflujo_flujo_dinero_tipo_de_flujo'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo_dinero',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes'),
        ),
    ]
