# Generated by Django 5.1.2 on 2024-11-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_datosextra_años_datosextra_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='acerca_de_mi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
